#!/bin/bash
echo "Exploring BeagleBone Chapter 5 Performance Test Code"
echo "Building the Executables"
gcc -pipe -Wall -O3 -fomit-frame-pointer -march=native -fopenmp n-body.c -o n-bodyc -lm
g++ -O3 n-body.cpp -o n-body
g++ -O3 --std=c++14  n-body2.cpp -o n-body2

echo "Building the Java Executable"
javac nbody.java

echo "Building the Rust Executable"
rustc -C opt-level=3 -C target-cpu=core2 -C lto -C codegen-units=1 -C llvm-args='-unroll-threshold=500' nbody.rs -o nbody.rust_run

echo "Finished Building the Programs"
