#!/bin/bash
echo -e "Building the C# Mono Code\n"
echo -e "You must have installed Mono on the RPi to run this test\n"
echo -e "  use sudo apt-get install mono-dmcs\n"

Duration="5000000"
mcs -optimize+ -platform:arm -out:nbody_csharp n-body.csharp

echo -e "Executing the C# Mono Code\n"
T="$(date +%s%N)"
./nbody_csharp $Duration
T="$(($(date +%s%N)-T))"
T=$((T/1000000))
echo "It took ${T} milliseconds to run the C# Mono test"
