######################################################################
# Automatically generated by qmake (3.0) Tue Aug 28 00:28:43 2018
######################################################################

TEMPLATE = app
TARGET = simpleQt
QT +=widgets
INCLUDEPATH += .

# Input
SOURCES += simpleQt.cpp
