######################################################################
# Automatically generated by qmake (2.01a) Thu May 15 03:07:20 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += simpleQt.cpp
