all: GTKsimple GTKtemperature

GTKsimple: 	
	g++ `pkg-config --libs --cflags glib-2.0 gtk+-2.0` GTKsimple.cpp -o gtksimple

GTKtemperature: 	
	g++ `pkg-config --libs --cflags glib-2.0 gtk+-2.0` GTKtemperature.cpp -o gtktemperature

