#!/bin/bash
g++ testADXL345.cpp ../../../library/libEBBLibrary.so -o testADXL345 -I"../../../library"
g++ SPITest.cpp ../../../library/libEBBLibrary.so -o SPITest -I"../../../library"
echo "Before executing testADXL345, ensure that the libEBBLibrary.so is in your path -- e.g., in /usr/lib"
