#!/bin/bash
g++ temperatureClientTest.cpp network/SocketClient.cpp -o temperatureClientTest -pthread
g++ temperatureServer.cpp network/SocketServer.cpp network/ConnectionHandler.cpp -o temperatureServer -pthread
